version: 2.1
jobs:
  say_hello:
    docker:
      - image:  circleci/node:13.8.0
    steps:
      - run: "echo Hello, "
  say_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: "echo World!"
workflows:
  say hello world:
    jobs:
      - say_hello
      - say_world:
          requires:
            - say_hello
