version: 2.1

jobs:
  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: exit 0
      - run:
          name: on error
          command: echo "Hello Error!"
          when: on_fail
      - run:
          name: on success
          command: echo "Hello Susccess!"
          when: on_success

workflows:
  my_workflow:
    jobs:
      - my_job
